version: "3.9"

services:
  redis-cluster:
    image: redis:latest
    container_name: redis-cluster
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
    ports:
      - 6300:6300
      - 6301:6301
      - 6302:6302

  redis-node1:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node1
    volumes:
      - ./node1.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
    ports:
      - 6300:6300

  redis-node2:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node2
    volumes:
      - ./node2.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
    ports:
      - 6301:6301

  redis-node3:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node3
    volumes:
      - ./node3.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
    ports:
      - 6302:6302

  redis-cluster-entry:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-cluster-entry
    command: redis-cli --cluster create 127.0.0.1:6300 127.0.0.1:6301 127.0.0.1:6302 --cluster-yes
    depends_on:
      - redis-cluster
      - redis-node1
      - redis-node2
      - redis-node3
